players:
    example:
        iron: true
        steel: false
        tin: false
        pewter: false
        brass: false
        zinc: false
        bronze: false
        copper: false
    exampleb:
        